In [1]:
import numpy as np
import pandas as pd
import FINITO
from FINITO import MEF1D

In [2]:
EXAMPLE = {
    "TYPE_ELEMENT": 0,
    "TYPE_SOLUTION": 0,
    "N_NODES": 23,
    "N_ELEMENTS": 24,  
    "N_MATERIALS": 2,
    "N_SECTIONS": 2,
    "N_DISPLACEMENTS": 6,
    "N_ELEMENTSLOADED": 0,
    "N_NODESLOADED": 21,
    "N_SPRINGS": 0,
    "COORDINATES": np.array([[0.00,0.00],
                            [4.50,0.00],
                            [0.00,3.00],
                            [0.75,3.00],
                            [1.50,3.00],
                            [2.25,3.00],
                            [3.00,3.00],
                            [3.75,3.00],
                            [4.50,3.00],
                            [0.00,6.00],
                            [0.75,6.00],
                            [1.50,6.00],
                            [2.25,6.00],
                            [3.00,6.00],
                            [3.75,6.00],
                            [4.50,6.00],
                            [0.00,9.00],
                            [0.75,9.00],
                            [1.50,9.00],
                            [2.25,9.00],
                            [3.00,9.00],
                            [3.75,9.00],
                            [4.50,9.00]]),
    "ELEMENTS": np.array([[0,2,1,1,0,0],
                            [2,3,1,1,0,0],
                            [3,4,1,1,0,0],
                            [4,5,1,1,0,0],
                            [5,6,1,1,0,0],
                            [6,7,1,1,0,0],
                            [7,8,1,1,0,0],
                            [8,1,1,1,0,0],
                            [2,9,1,1,0,0],
                            [9,10,1,1,0,0],
                            [10,11,1,1,0,0],
                            [11,12,1,1,0,0],
                            [12,13,1,1,0,0],
                            [13,14,1,1,0,0],
                            [14,15,1,1,0,0],
                            [15,8,1,1,0,0],
                            [9,16,1,1,0,0],
                            [16,17,1,1,0,0],
                            [17,18,1,1,0,0],
                            [18,19,1,1,0,0],
                            [19,20,1,1,0,0],
                            [20,21,1,1,0,0],
                            [21,22,1,1,0,0],
                            [22,15,1,1,0,0]]),
    "MATERIALS": np.array([[3.1E7,0.20,25,0.000010],
                            [3.1E7,0.20,25,0.000010]]),
    "SECTIONS": np.array([[6.300e-02,1.063e-03,1.063e-03,0.1,0.1], 
                            [6.300e-02,1.063e-03,1.063e-03,0.1,0.1]]),
    "PRESCRIBED DISPLACEMENTS": np.array([[0,0,0],
                                            [0,1,0],
                                            [0,2,0],
                                            [1,0,0],
                                            [1,1,0],
                                            [1,2,0]]),
    "ELEMENT LOADS": None,
    "NODAL LOADS": np.array([[2,1,-10],
                                [3,1,-10],
                                [4,1,-10],
                                [5,1,-10],
                                [6,1,-10],
                                [7,1,-10],
                                [8,1,-10],
                                [9,1,-10],
                                [10,1,-10],
                                [11,1,-10],
                                [12,1,-10],
                                [13,1,-10],
                                [14,1,-10],
                                [15,1,-10],
                                [16,1,-10],
                                [17,1,-10],
                                [18,1,-10],
                                [19,1,-10],
                                [20,1,-10],
                                [21,1,-10],
                                [22,1,-10]]),
  "SPRINGS": None,
  }

In [3]:
RESULTS = MEF1D(DICTIONARY = EXAMPLE)

In [4]:
RESULTS_BAR_0 = pd.DataFrame(data=RESULTS[2])
RESULTS_BAR_0.head(50)

,X,UX,UY,UZ,N,V,M,ID_ELEMENT
0,0.000,0.000340,-0.000295,-0.000214,37.925711,10.180724,1.670201,2
1,0.075,-1989.000000,-1989.000000,-1989.000000,37.925711,10.180724,2.433756,2
2,0.150,-1989.000000,-1989.000000,-1989.000000,37.925711,10.180724,3.197310,2
3,0.225,-1989.000000,-1989.000000,-1989.000000,37.925711,10.180724,3.960864,2
4,0.300,-1989.000000,-1989.000000,-1989.000000,37.925711,10.180724,4.724418,2
5,0.375,-1989.000000,-1989.000000,-1989.000000,37.925711,10.180724,5.487973,2
6,0.450,-1989.000000,-1989.000000,-1989.000000,37.925711,10.180724,6.251527,2
7,0.525,-1989.000000,-1989.000000,-1989.000000,37.925711,10.180724,7.015081,2
8,0.600,-1989.000000,-1989.000000,-1989.000000,37.925711,10.180724,7.778635,2
9,0.675,-1989.000000,-1989.000000,-1989.000000,37.925711,10.180724,8.542190,2
10,0.750,0.000354,-0.000419,-0.000089,37.925711,10.180724,9.305744,2

In [5]:
Δ = RESULTS_BAR_0.iloc[2]
Δ.head()

X        0.150000
UX   -1989.000000
UY   -1989.000000
UZ   -1989.000000
N       37.925711
Name: 2, dtype: float64

In [6]:
print(Δ['X'])

0.15

In [7]:
print(450 / 8)

56.25

In [8]:
RESULTS_BAR_0 = RESULTS[2]
RESULTS_BAR_0

{'X': array([0.   , 0.075, 0.15 , 0.225, 0.3  , 0.375, 0.45 , 0.525, 0.6  ,
        0.675, 0.75 ]),
 'UX': array([ 3.39829105e-04, -1.98900000e+03, -1.98900000e+03, -1.98900000e+03,
        -1.98900000e+03, -1.98900000e+03, -1.98900000e+03, -1.98900000e+03,
        -1.98900000e+03, -1.98900000e+03,  3.54393511e-04]),
 'UY': array([-2.94850197e-04, -1.98900000e+03, -1.98900000e+03, -1.98900000e+03,
        -1.98900000e+03, -1.98900000e+03, -1.98900000e+03, -1.98900000e+03,
        -1.98900000e+03, -1.98900000e+03, -4.19392763e-04]),
 'UZ': array([-2.14027145e-04, -1.98900000e+03, -1.98900000e+03, -1.98900000e+03,
        -1.98900000e+03, -1.98900000e+03, -1.98900000e+03, -1.98900000e+03,
        -1.98900000e+03, -1.98900000e+03, -8.91226004e-05]),
 'N': array([37.92571098, 37.92571098, 37.92571098, 37.92571098, 37.92571098,
        37.92571098, 37.92571098, 37.92571098, 37.92571098, 37.92571098,
        37.92571098]),
 'V': array([10.18072375, 10.18072375, 10.18072375, 10.18072375, 10.18072375,
        10.18072375, 10.18072375, 10.18072375, 10.18072375, 10.18072375,
        10.18072375]),
 'M': array([1.67020122, 2.43375551, 3.19730979, 3.96086407, 4.72441835,
        5.48797263, 6.25152691, 7.01508119, 7.77863548, 8.54218976,
        9.30574404]),
 'ID_ELEMENT': 2}